Counter; to count the number of books in the database
Jake-Fischer/readinglist pull request #16
Opened 2021-09-12 03:36 UTC by mkhalil7625

@ew3361zh

2021-09-13 01:51 UTC, ew3361zh requested changes
Nice work!
I have a couple things to suggest:
1. Make all the words in the menu option capitalized to match the formatting for the rest of the menu options (right now the word "total" is not capitalized).
2. Add an if/else block for the book_count function to account for grammar. So I would do something like:
if count == 1:
 print('There is 1 book in the database')
else:
print(f'There are {count} books in the database'}

Otherwise looks great!

2021-09-13 02:31 UTC, ew3361zh approved these changes
looks excellent and working well when I pulled it locally!

2021-09-13 02:33 UTC, merged

2021-09-13 02:42 UTC, mkhalil7625 commented
@ew3361zh Thank you for your feedback. I have incorporated your ideas and pushed the code into the branch, please review and let me know if you recommend other updates.
Thanks!

2021-09-13 02:47 UTC, ew3361zh commented
@mkhalil7625 I did the "approve" changes in the review section and then merged the pull request. We should probably figure out the order of who's doing the merge so we don't accidentally double that up or do it too soon. Apologies if I jumped the gun. Nice work!

2021-09-13 03:35 UTC, mkhalil7625 commented
@ew3361zh No worries, I was writing my previous message when my daughter interrupted before I hit comment :)  so it appeared after your closing the request. 
I think if we always have the option to rollback our changes if needed or to create another branch for further updates

2021-09-28 23:19 UTC, claraj commented on main.py
> +    menu.add_option('8','Show Total Book Count', book_count)
Minor style note - add a space after the comma, similar to the lines before.

2021-09-28 23:19 UTC, claraj commented on main.py
> +    if count==1:
Style - spaces around operators like == is recommended
`if count == 1:`

2021-09-28 23:20 UTC, claraj reviewed
Small style notes